

services:
  db:
    image: postgres:15
    container_name: project_manager_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: project_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  minio:
    image: minio/minio:latest
    container_name: project_manager_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ACCESS_KEY: miniodocker
      MINIO_SECRET_KEY: miniodocker
      MINIO_SERVER_URL: "http://localhost:9005"

    ports:
      - "9005:9000"
      - "9006:9001"
    volumes:
      - minio_data:/data


  backend:
    image: project_manager_api:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project_manager_api
    depends_on:
      - db
      - minio
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/project_db
      - AWS_S3_ENDPOINT_URL=http://minio:9000
      - PUBLIC_S3_HOST=http://localhost:9005
      - AWS_ACCESS_KEY_ID=miniodocker
      - AWS_SECRET_ACCESS_KEY=miniodocker
      - S3_BUCKET_NAME=docker-bucket

    volumes:
      - .:/app


volumes:
  pgdata:
  minio_data:
