name: Python Application CI

on:

  push:
    branches: [ master ]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:

         python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r pip_requirements.txt

      - name: Lint with flake8
        run : |
          flake8 backend/ --count --ignore=E501,W503,W504 --max-line-length=88 --show-source --statistics

      - name: Check formatting with black
        run : |
          black backend/ --check
